### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by SIMULATAN**

### CODE REVIEW

**Review by RealYusufIsmail — CHANGES_REQUESTED** [review]
The working on something is unnecessary.

**Comment by RealYusufIsmail** [comment]
> > I would have something called feature change and in which you explain what you are changing and if it affects the user on discord or it is an api change/dependency update etc.
> 
> Well that would be a changelog, my idea was to add the possibility to tell other people that you're working on something so they can adapt and for example hold on with changes that rely on the old implementation

Yeah i mean have it were they have to say what they are changing and if it affects the user on discord.

**Comment by SIMULATAN** [comment]
> > > I would have something called feature change and in which you explain what you are changing and if it affects the user on discord or it is an api change/dependency update etc.
> > 
> > Well that would be a changelog, my idea was to add the possibility to tell other people that you're working on something so they can adapt and for example hold on with changes that rely on the old implementation
> 
> Yeah i mean have it were they have to say what they are changing and if it affects the user on discord.

Okay
How should I call it then?

**Comment by RealYusufIsmail** [comment]
Have a look at [this](https://github.com/DV8FromTheWorld/JDA/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by SIMULATAN** [comment]
> Have a look at [this](https://github.com/DV8FromTheWorld/JDA/blob/master/.github/PULL_REQUEST_TEMPLATE.md?rgh-link-date=2022-04-08T03%3A08%3A53Z)

I'll add that

**Review by RealYusufIsmail — APPROVED** [review]
I approve the change's since you are updating the working on

**Comment by SIMULATAN** [comment]
@RealYusufIsmail changed some things, please review the PR again.

(GH somehow doesn't do anything when I click the request review button)

**Comment by RealYusufIsmail** [comment]
> @RealYusufIsmail changed some things, please review the PR again.
> 
> (GH somehow doesn't do anything when I click the request review button)

Thats because i have no review perms.

**Review by RealYusufIsmail — APPROVED** [review]
All good.

**Pull request merged**
